# This file is available under the following license:
# under LGPL 2.1 (LICENSE.TXT) Copyright 2023 Torsten Friebe <tfr@users.sourceforge.net>
name: Docker Image CI

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [ "main" ]

jobs:

  build-3_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push v3.4
        uses: docker/build-push-action@v6
        with:
          context: ./3.4
          platforms: linux/amd64,linux/arm64
          push: true
          tags: deegree/deegree3-docker:v3.4.35,deegree/deegree3-docker:v3.4,deegree/deegree3-docker:3.4
  build-3_5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push v3.5
        uses: docker/build-push-action@v6
        with:
          context: ./3.5
          platforms: linux/amd64,linux/arm64
          push: true
          tags: deegree/deegree3-docker:3.5.16,deegree/deegree3-docker:3.5
  build-3_6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push v3.6
        uses: docker/build-push-action@v6
        with:
          context: ./3.6
          platforms: linux/amd64,linux/arm64
          push: true
          tags: deegree/deegree3-docker:3.6.0,deegree/deegree3-docker:3.6,deegree/deegree3-docker:latest